spring:
  application:
    name: auth-service  
  swagger:
    autostart: false
  mvc:
    log-resolved-exception: false
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://develophost:9411/    
    service:
      name: auth-service
    sender:
      type: rabbit
    storage:
      type: elasticsearch
      elasticsearch:
        hosts: develophost:9200            
  rabbitmq:
    host: develophost
    port: 5672
    username: admin
    password: admin
  security:
    oauth2:
      client:
        registration:
          keycloak:            
            client-id: spring-microservices-template-auth-service
            client-secret: 6zLKJnHUfyXSpa9QEwzXNADnVuZ34oqc
            authorization-grant-type: authorization_code            
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://develophost:18080/auth/realms/spring-microservices-template
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          jwk-set-uri: http://develophost:18080/auth/realms/spring-microservices-template/protocol/openid-connect/certs                           

springdoc:
  api-docs:
    path: /api-docs    

eureka:
  instance:
    hostname: develophost
  client:
    region: default
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 20
    serviceUrl:
      defaultZone: http://admin:admin@develophost:8082/template/eureka/    

keycloak-server:
  server-url: develophost:18080/auth
  gateway-client-id: spring-microservices-template-gateway-service
  gateway-client-secret: 756b0558-018b-4809-b478-bd5b4995d325
  admin:
    username: admin
    password: admin  

server:  
  port: 8085
  forward-headers-strategy: framework
  servlet:
    context-path: /template
