spring:
  application:
    name: book-service  
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  liquibase:
    change-log: classpath:db/db.changelog.xml
  datasource:
    url: jdbc:postgresql://develophost:5432/microservices_template_book_service_db
    username: postgres
    password: root
  swagger:
    autostart: false
  mvc:
    log-resolved-exception: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html  

eureka:
  instance:
    hostname: develophost
  client:
    region: default
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 20
    serviceUrl:
      defaultZone: http://develophost:8082/template/eureka/    

server:
  port: 8083
  forward-headers-strategy: framework
  servlet:
    context-path: /template
