spring:
  application:
    name: book-service  
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/db.changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices_template_book_service_db
    username: postgres
    password: root
  swagger:
    autostart: false
  mvc:
    log-resolved-exception: false
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
    collector:
      kafka: 
        bootstrap-servers: localhost:9092
    service:
      name: book-service
    sender:
      type: kafka
    kafka:
      topic: zipkin  
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    client-id: book-service
    consumer:
      auto-offset-reset: earliest
      properties:
        allow.auto.create.topics: true 
    producer:
      auto-offset-reset: earliest        

springdoc:
  api-docs:
    path: /api-docs    

eureka:
  instance:
    hostname: localhost
  client:
    region: default
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 20
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8082/template/eureka/    

server:  
  port: 8083
  forward-headers-strategy: framework
  servlet:
    context-path: /template
