spring:
  application:
    name: book-service  
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  liquibase:
    change-log: classpath:db/db.changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices_template_book_service_db
    username: postgres
    password: root
  swagger:
    autostart: false
  mvc:
    log-resolved-exception: false

springdoc:
  api-docs:
    path: /book-api-docs
  swagger-ui:
    use-root-path: true      
    path: /swagger-ui.html  

eureka:
  instance:
    hostname: localhost
  client:
    region: default
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 20
    serviceUrl:
      defaultZone: http://localhost:8082/template/eureka/    

server:  
  port: 8083
  servlet:
    context-path: /template
