spring:
  application:
    name: discovery-service  

eureka:
  instance:
    hostname: develophost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://develophost:8083/eureka/    

server:
  port: 8083
  servlet:
    context-path: /template
