spring:
  application:
    name: discovery-server  

eureka:
  instance:
    hostname: 127.1.1.1
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.1.1.1:8083/eureka/    

server:
  port: 8083
  servlet:
    context-path: /template
