spring:
  application:
    name: discovery-service

discovery:
  server:
    security:
      username: admin
      password: admin

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${discovery.server.security.username}:${discovery.server.security.password}@localhost:8082/eureka/    

server:
  port: 8082
  servlet:
    context-path: /template
