spring:
  application:
    name: discovery-service
  security:
    user:
      name: admin
      password: admin
      roles: SYSTEM    

eureka:
  instance:
    hostname: develophost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${spring.security.security.user.name}:${spring.security.security.user.password}@develophost:8082/eureka/    

server:
  port: 8082
  servlet:
    context-path: /template
