spring:
  application:
    name: discovery-service
  security:
    user:
      name: admin
      password: admin
      roles: SYSTEM
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session:template
  redis:
    host: localhost
    port: 6379
    password: admin      

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8082/eureka/    

server:
  port: 8082
  servlet:
    context-path: /template
