spring:
  application:
    name: gateway-service    
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/    
    service:
      name: gateway-service
    sender:
      type: rabbit
    storage:
      type: elasticsearch
      elasticsearch:
        hosts: localhost:9200            
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin      

eureka:  
  client:
    region: default
    registryFetchIntervalSeconds: 20  
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8082/db-suite/eureka/

zuul:
  host:
    connect-timeout-millis: 60000
  routes:      
    discovery-service:
      path: /discovery-service/**
      sensitive-headers: 
      url: http://localhost:8082/db-suite
    vendor-service:
      path: /vendor-service/**
      sensitive-headers: 
      url: http://localhost:8083/db-suite
    user-service:
      path: /user-service/**
      sensitive-headers: 
      url: http://localhost:8084/db-suite
    metadata-service:
      path: /metadata-service/**
      sensitive-headers: 
      url: http://localhost:8085/db-suite                           

hystrix:
  shareSecurityContext: true 
  command:
    discovery-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    vendor-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    user-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    metadata-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000  

springdoc:
  api-docs:
    enabled: true    
  swagger-ui:    
    urls:      
      - name: vendor-service
        url: /vendor-service/api-docs
      - name: user-service
        url: /user-service/api-docs
      - name: metadata-service
        url: /metadata-service/api-docs

server:
  port: 8080
  forward-headers-strategy: framework  
  servlet:
    context-path: /db-suite        
