spring:
  application:
    name: gateway-service

eureka:  
  client:
    region: default
    registryFetchIntervalSeconds: 20  
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://develophost:8082/template/eureka/

zuul:
  routes:
    book-service:
      path: /book-service/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://develophost:8083/template
    discovery-service:
      path: /discovery-service/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://develophost:8082/template                       

springdoc:
  api-docs:
    enabled: true    
  swagger-ui:    
    urls:
      - name: book-service
        url: ${zuul.routes.book-service.url}/api-docs

hystrix:
  command:
      book-service:
          execution:
              isolation:
                  thread:
                      timeoutInMilliseconds: 600000
      discovery-service:
          execution:
              isolation:
                  thread:
                      timeoutInMilliseconds: 600000                

server:
  port: 8080
  servlet:
    context-path: /template
