spring:
  application:
    name: gateway-service
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/    
    service:
      name: gateway-service
    sender:
      type: rabbit
    storage:
      type: elasticsearch
      elasticsearch:
        hosts: localhost:9200            
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  security:
    oauth2:
      client:
        registration:
          keycloak:            
            client-id: spring-microservices-template-gateway-service
            client-secret: yj72kNVj20RAQaKolxYsKqo7ecwnTg2v
            authorization-grant-type: authorization_code            
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:18080/auth/realms/spring-microservices-template
            user-name-attribute: preferred_username                                        

eureka:  
  client:
    region: default
    registryFetchIntervalSeconds: 20  
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8082/template/eureka/

zuul:
  routes:
    book-service:
      path: /book-service/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8083/template
    user-service:
      path: /user-service/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8084/template  
    discovery-service:
      path: /discovery-service/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8082/template   
    auth-service:
      path: /auth-service/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8085/template                      


hystrix:
  command:
      book-service:
          execution:
              isolation:
                  thread:
                      timeoutInMilliseconds: 600000
      user-service:
          execution:
              isolation:
                  thread:
                      timeoutInMilliseconds: 600000
      discovery-service:
          execution:
              isolation:
                  thread:
                      timeoutInMilliseconds: 600000
      auth-service:
          execution:
              isolation:
                  thread:
                      timeoutInMilliseconds: 600000                    

springdoc:
  api-docs:
    enabled: true    
  swagger-ui:    
    urls:
      - name: book-service
        url: /book-service/api-docs
      - name: user-service
        url: /user-service/api-docs
      - name: auth-service
        url: /auth-service/api-docs      

server:
  port: 8080
  forward-headers-strategy: framework  
  servlet:
    context-path: /template  
