spring:
  application:
    name: gateway-service

eureka:  
  client:
    region: default
    registryFetchIntervalSeconds: 20  
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8082/template/eureka/

zuul:
  routes:
    book-service:
      path: /book-service/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8083/template
    discovery-service:
      path: /discovery-service/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8082/template                       


hystrix:
  command:
      book-service:
          execution:
              isolation:
                  thread:
                      timeoutInMilliseconds: 600000
      discovery-service:
          execution:
              isolation:
                  thread:
                      timeoutInMilliseconds: 600000    

server:
  port: 8080  
  servlet:
    context-path: /template

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    configUrl: http://localhost:8080/template/api-docs/swagger-config
    path: /api.html
    urls:
      - name: book-service
        url: ${zuul.routes.book-service.url}/api-docs    
