spring:
  application:
    name: gateway-service
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://develophost:9411/    
    service:
      name: gateway-service
    sender:
      type: kafka
    kafka:
      topic: zipkin  
  kafka:
    bootstrap-servers: develophost:9092
    client-id: gateway-service            

eureka:  
  client:
    region: default
    registryFetchIntervalSeconds: 20  
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://admin:admin@develophost:8082/template/eureka/

zuul:
  routes:
    book-service:
      path: /book-service/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://develophost:8083/template
    user-service:
      path: /user-service/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://develophost:8084/template
    discovery-service:
      path: /discovery-service/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://develophost:8082/template                       

springdoc:
  api-docs:
    enabled: true    
  swagger-ui:    
    urls:
      - name: book-service
        url: /book-service/api-docs
      - name: user-service
        url: /user-service/api-docs  

hystrix:
  command:
      book-service:
          execution:
              isolation:
                  thread:
                      timeoutInMilliseconds: 600000
      user-service:
          execution:
              isolation:
                  thread:
                      timeoutInMilliseconds: 600000
      discovery-service:
          execution:
              isolation:
                  thread:
                      timeoutInMilliseconds: 600000                

server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    context-path: /template
