spring:
  application:
    name: gateway-service
  webflux:
    base-path: /template  
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/    
    service:
      name: gateway-service
    sender:
      type: rabbit
    storage:
      type: elasticsearch
      elasticsearch:
        hosts: localhost:9200            
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true 
      routes:
       - id: book-service
         uri: lb://book-service/template
         predicates:
          - Path=/book-service/**
         filters:
          - RewritePath=/book-service/(?<path>.*), /$\{path}           
       - id: user-service
         uri: lb://user-service/template
         predicates:
          - Path=/user-service/**
         filters:
          - RewritePath=/user-service/(?<path>.*), /$\{path}           
       - id: auth-service
         uri: lb://auth-service/template
         predicates:
          - Path=/auth-service/**
         filters:
          - RewritePath=/auth-service/(?<path>.*), /$\{path}
       - id: openapi
         uri: http://localhost:8080/template
         predicates:
          - Path=/v3/api-docs/**
         filters:
          - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
                                                                                                               

eureka:  
  client:
    region: default
    registryFetchIntervalSeconds: 20  
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8082/template/eureka/

springdoc:
  api-docs:
    enabled: true    
  swagger-ui:    
    urls:
      - name: book-service
        url: /v3/api-docs/book-service
      - name: user-service
        url: /v3/api-docs/user-service
      - name: auth-service
        url: /v3/api-docs/auth-service      

server:
  port: 8080
  forward-headers-strategy: framework  
  servlet:
    context-path: /template  
