spring:
  application:
    name: gateway-server

eureka:  
  client:
    region: default
    registryFetchIntervalSeconds: 20  
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8082/template/eureka/

zuul:
  routes:
    book-service:
      path: /book-service/**
      sensitive-headers: Set-Cookie,Authorization
    discovery-server:
      path: /discovery-server/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8082/template                       


hystrix:
  command:
      book-service:
          execution:
              isolation:
                  thread:
                      timeoutInMilliseconds: 600000
      discovery-server:
          execution:
              isolation:
                  thread:
                      timeoutInMilliseconds: 600000                

server:
  port: 8083
  servlet:
    context-path: /template
