spring:
  application:
    name: trace-service
  security:
    user:
      name: admin
      password: admin
      roles: SYSTEM  

eureka:
  instance:
    hostname: develophost
  client:
    region: default
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 20
    serviceUrl:
      defaultZone: http://admin:admin@develophost:8082/template/eureka/    

logging:
  level:
    org:
      springframework:
        web: debug

server:
  port: 8085
  servlet:
    context-path: /template
